# Generated by Django 4.1.1 on 2023-04-15 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CITY_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='STATE_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='login_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.TextField(max_length=8)),
                ('phone_no', models.BigIntegerField()),
                ('role', models.CharField(choices=[('Designer', 'Designer'), ('User', 'User')], max_length=10)),
                ('city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city_table')),
                ('state_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state_table')),
            ],
        ),
        migrations.CreateModel(
            name='FEEDBACK_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RATINGS', models.CharField(max_length=300)),
                ('COMMENT', models.CharField(default='', max_length=300)),
                ('login_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='detail_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_desc', models.CharField(max_length=300)),
                ('i_experience', models.IntegerField(max_length=10)),
                ('login_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='designs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
                ('Design_Description', models.TextField()),
                ('dimage', models.ImageField(null=True, upload_to='photos')),
                ('login_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.CreateModel(
            name='complain_TABLE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=3)),
                ('Description', models.CharField(default='', max_length=300)),
                ('i_ID', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.detail_table')),
                ('login_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
        migrations.AddField(
            model_name='city_table',
            name='state_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state_table'),
        ),
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approx_budget', models.CharField(max_length=35)),
                ('b_status', models.CharField(choices=[('0', 'NOT APPROVED'), ('1', 'APPROVED')], max_length=50)),
                ('d_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.designs')),
                ('login_id', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.login_table')),
            ],
        ),
    ]
