# Generated by Django 4.1.1 on 2023-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bidding',
            name='show_interest_button',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bidding',
            name='b_status',
            field=models.CharField(choices=[('0', 'unapproved'), ('1', 'approved'), ('2', 'rejected')], max_length=50),
        ),
    ]
