# Generated by Django 5.0.3 on 2024-03-04 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_feedback_table_ratings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
