from django.urls import path
from myapp import views

urlpatterns = [
    path('', views.home, name='index.html'),
    path('basic', views.basic, name='basic'),
    path('about', views.about, name='about'),
    path("login", views.login, name="login"),
    path("signup", views.signup, name="signup"),
    path("viewdata", views.viewdata, name="viewdata"),
    path('checkuser', views.checklogin, name='checkuser'),
    path('logout', views.logout, name='logout'),
    path('completeprofile', views.completeprofile, name='completeprofile'),
    path('completeprofilesubmit', views.completeprofilesubmit, name='completeprofilesubmit'),
    path('designerprofile', views.designerprofile, name='designerprofile'),
    path('editprofiledesgn', views.editprofiledesgn, name='editprofiledesgn'),
    path('editprofiledesgnsubmit', views.editprofiledesgnsubmit, name='editprofiledesgnsubmit'),
    path('changepw', views.changepw, name='changepw'),
    path('changepwsubmit', views.changepwsubmit, name='changepwsubmit'),
    path('profile', views.profile, name='profile'),
    path('editprofile', views.editprofile, name='editprofile'),
    path('editprofilesubmit', views.editprofilesubmit, name='editprofilesubmit'),
    path('uploaddesign', views.uploaddesign, name='uploaddesign'),
    path('designsubmit', views.designsubmit, name='designsubmit'),
    path('viewdesigns', views.viewdesigns, name='viewdesigns'),
    path('viewdesignbids', views.viewdesignbids, name='viewdesignbids'),
    path('makeabid', views.makeabid, name='makeabid'),
    path('mybids', views.mybids, name='mybids'),
    path('mydesigns', views.mydesigns, name='mydesigns'),
    path('designers', views.designers, name='designers'),
    path('feedback', views.feedback, name='feedback'),
    path('feedbacksubmit', views.feedbacksubmit, name='feedbacksubmit'),
    path('complain', views.complain, name='complain'),
    path('complainsubmit', views.complainsubmit, name='complainsubmit'),
    path('approveddesign', views.approveddesign, name='approveddesign'),
    path('paymentsubmit', views.paymentsubmit, name='paymentsubmit'),
    path("makepayment/<int:mpid>", views.makepayment, name="makepayment"),
    path("designsingle/<int:dsid>", views.designsingle, name="designsingle"),
    path("designerprofiledata/<int:dpdid>", views.designerprofiledata, name="designerprofiledata"),
    path("approvebid/<int:abid>", views.approvebid, name="approvebid"),
    path("rejectbid/<int:rbid>", views.rejectbid, name="rejectbid"),
    path("deletebid/<int:dbid>", views.deletebid, name="deletebid"),
    path("deletedesign/<int:ddid>", views.deletedesign, name="deletedesign"),
]

